pipeline {
    agent any

    stages {
        stage('File Copy') {
            steps {
                sh "env"
                echo 'Copy from one file to another file'
                sh 'cp test test1'
            }
        }
        stage('Show Content Of First File') {
            steps {
                echo 'Content of first file'
                sh 'cat test'
            }
        }
        stage('Show Content Of Second File') {
            steps {
                sh "echo 'Added New line to test1 ${env.Branch}'  >> test1"
                echo 'Content of changed second file'
                sh 'cat test1'
                sh 'cat test'
            }
        }
    }
}
